Implement log system
kworkflow/patch-hub pull request #37
Opened 2024-09-02 14:56 UTC by OJarrisonn

This PR ain't complete so **DO NOT MERGE IT YET**, this is just to discuss around the current status of this feature

- Introduces a new dependency: [chrono](https://crates.io/crates/chrono)
- Introduces a new configuration option: `log_path`
- Adds a `Logger` singleton that is non-thread safe
- Known issue: the user must manually create `log_path` folder before using
- Known issue: memory utilization: log entries are stored both in memory and in disk
- No logging level (INFO, WARN, FAIL), etc

2024-09-05 15:59 UTC, davidbtadokoro commented
Hi @OJarrisonn, thanks a lot for this PR! I will take a closer look at it to begin discussions ASAP.

2024-09-10 17:16 UTC, davidbtadokoro requested changes
Hi @OJarrisonn, and thank you so much for this PR! Sorry for the delay, but I wanted to give it the attention it deserves.

## Comments about the PR

Before bringing my thoughts and starting the "high-level" discussion, I want to address small things about the PR itself, which I think you didn't bother with because of the "begin discussion" idea of the PR. I am just laying them here for the record and for when we move on to refine and merge it.

1. You can squash all commits into one
2. When reviewing and testing the change, I produced feedback that will be important to refinement for when we merge it, so I left some inline review comments
3. Always add your signed-off by

## Discussion about the feature itself

I've tested a handful of scenarios and, overall, the feature works as intended :+1: :+1:

IMHO, we are okay in robustness as we persist logs on the fly and keep a separate data structure for printing (the change to the panic hook also helps avoid losing logs). The restriction on single-threaded isn't an issue for the moment, so I vouch for crossing this bridge when we need :sweat_smile: 

At first, I tried adapting your implementation to remove the buffer with the vector of strings. As we are persisting the logs immediately, I thought it was redundant to keep an identical copy in memory instead of just printing the contents of the log file when flushing. However, I gave up on this idea because we probably won't want to print every log to the terminal at the end of execution. On the other hand, there will be some warnings and errors that we want the user to be aware of, so I am leaning towards having (1) the log file that will amass **all** events that are logged and (2) a buffer for the "logs to print". In the future, it wouldn't be hard to add a "verbose" flag/config to patch-hub to print all logs to the terminal, in which case we would fall in the current implementation, i.e., the buffer to print and file contents will be the same.

Below is a draft of change on `write` for logging with two levels (to print, or not) in which I just add a boolean, essentially. 

```rust
    pub fn write(&mut self, msg: &str, print: bool) {
        let msg = format!(
            "[{}] {}",
            chrono::Local::now().format("%Y-%m-%d %H:%M:%S"),
            msg
        );

        let log_file = self.log_file
            .as_mut()
            .expect("Log file not initialized, make sure to call Logger::init_log_file() before writing to the log file");
        writeln!(log_file, "{msg}")
            .expect("Failed to write to log file");

        if print {
            self.logs_to_print.push(msg);
        }
    }
```

Obs.: I've renamed `buffer` to `logs_to_print`.

## Conclusion

I think we are on the right track and that this isn't so raw as you've said :rofl: 

Anyway, hit me with your thoughts, and remember that I am open to discussing any points I've brought up.

Great work!!!

2024-09-11 13:12 UTC, OJarrisonn commented on src/app/config.rs
> +    /// A folder inside the `patch-hub/logs` directory
I like more verbose documentation but i applied your suggestion

2024-09-11 13:15 UTC, OJarrisonn commented on src/app/logging.rs
> +    /// ```
We do have examples in the other functions, but i think it's worth to show the usage of a function in it's documentation.

2024-09-11 13:20 UTC, OJarrisonn commented on src/app/logging.rs
> +            let path = config.logs_path.clone();
Also, no need to clone it

2024-09-11 13:25 UTC, OJarrisonn commented on src/app.rs
> +        Logger::logger().write("Patch-hub started");
Sure thing

2024-09-12 21:54 UTC, davidbtadokoro commented
Hi @OJarrisonn, and thank you so much for the update! Also, marvelous work on the logging levels :+1: 

I've made changes to your PR, which you can check at [this branch](https://github.com/kworkflow/patch-hub/tree/OJarrisonn-logging-reviewed). Note that the commit messages contain a `Maintainer edits` section that overviews my modifications.

 If you agree with this proposal, we can move to merging!

2024-09-12 23:42 UTC, OJarrisonn commented
I just disagree with the changes in the fields names for `Logger`, i rather use shorter names like: `file`, `filepath`, `logs` and `level`

Also, was the log level filtering logic really inverted? `level <= self.print_level` means that if we set the filter level to `Warn` we will only print `Info` and `Warn` logs, and discard `Error`. Is this really the expected behaviour?

2024-09-13 00:12 UTC, davidbtadokoro commented
> I just disagree with the changes in the fields names for `Logger`, i rather use shorter names like: `file`, `filepath`, `logs` and `level`

I agree that whenever possible, we should favor shorter names. By now, you've gathered that I am really verbose in names :sweat_smile: , but at this time, I think `logs` and `level` is too ambiguous. Imagine someone who first sees the code; the name `logs` would prompt him to think that this vector will amass all logs, while this isn't true; also, `level` doesn't convey its means.

> Also, was the log level filtering logic really inverted? `level <= self.print_level` means that if we set the filter level to `Warn` we will only print `Info` and `Warn` logs, and discard `Error`. Is this really the expected behaviour?

Unfortunately, it is indeed inverted... Try adding a `warn()` and an `error()` right below the `info("patch-hub started")` and changing the print level of the Logger to `Warning`. Notice that the warning and the error will be printed when the warning and info should be printed instead.

Simulating the code, if the precedence is `Info < Warning < Error`, if `self.print_level == Warning`, the check

```rust
if self.print_level <= Info
``` 

will be false, making this inversion...

2024-09-13 12:21 UTC, OJarrisonn commented
Yeah, my approach is to print logs that are more severe than the filter level. We should always print the errors, while Info aint always relevant to the common user. Error messages always are relevant so fhe user might try to fix it by himself

Remember that the users of patch-hub are kernel developers, so we must provide the kind of logging that a developer might expect

In your approach we will always see the "patch-hub started" message when closing the app. Is this messeage really that important that we always print it to the terminal?

2024-09-13 13:36 UTC, OJarrisonn commented
Yes

2024-09-13 13:42 UTC, davidbtadokoro commented
Nice, going to do this soon.

Just as a head up, I might still have to solve some merge conflicts due to the last merged change. This probably won't change anything "important" or that we discussed, but just to keep the process transparent.

2024-09-13 15:58 UTC, davidbtadokoro commented
Hey @OJarrisonn, just merged the change into the unstable branch :+1: 

Thank you so much for your continuous effort and great work! The logging feature looks really neat and will be crucial for users and developers alike :fire:

2024-09-13 15:58 UTC, closed without merging